"""empty message

Revision ID: 68272760b5c4
Revises: 
Create Date: 2023-06-09 16:30:37.725317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68272760b5c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_post_id_fkey', type_='foreignkey')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_banner', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_banner')

    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('image_post_id_fkey', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###
